### ISSUE TITLE
readme missing

### ISSUE THREAD

**Issue by Lartu** [dysoco/chp8#1]
hi there I see you don't have a weadme uwu
it would be nicey wisey if you had one u///u * giggles *
that way winney-meaney people could wead what youw pwoject is about nwn

ok have fun i hope you fix this xD * starts twerking * 

xoxoxoxo

**Comment by Lartu** [comment]
pls fix asap very important ⚙︎⎶⚙︎

**Comment by Lartu** [comment]
k bye thx

**Comment by Lartu** [comment]
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non maximus lorem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam aliquet congue nisl vitae consequat. Donec viverra elementum fermentum. Etiam fringilla pretium elit, nec vulputate nunc euismod in. Maecenas rhoncus, turpis eu sagittis porttitor, odio quam tristique nulla, sit amet feugiat lacus dui eu massa. Proin quis blandit elit. Nam porttitor malesuada sodales. Donec sit amet libero in massa luctus porttitor vel sed augue. Sed non consectetur orci, eu rhoncus odio. Nullam dapibus nisi et arcu dignissim, non tempor nibh aliquet. Suspendisse arcu ligula, vestibulum ut leo sit amet, dignissim bibendum diam.

Nam vel blandit nisi. Aliquam posuere eleifend risus ut sollicitudin. Vestibulum vestibulum orci a lobortis rhoncus. Curabitur maximus convallis vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin at arcu nisl. Aenean pellentesque euismod vehicula. Aliquam non congue dolor, vel eleifend urna. Curabitur congue nisi ac nunc vulputate, quis viverra orci placerat. Ut tempor nec justo id pretium.

Aliquam sollicitudin elit a tempus consequat. Nullam lacinia finibus ex sit amet vulputate. Donec luctus, nibh vel accumsan consequat, enim ipsum vulputate mauris, sed vehicula est nibh vitae quam. Etiam ipsum ligula, efficitur eu est nec, ultrices scelerisque risus. Nam sit amet nibh mi. Nulla vitae dui bibendum, imperdiet eros ut, volutpat nulla. Quisque dictum finibus arcu, at pretium felis convallis ullamcorper. Proin et euismod augue. Sed sodales urna quis auctor condimentum. In hac habitasse platea dictumst. Nullam pretium, justo vel facilisis tincidunt, magna leo vehicula nunc, at egestas ipsum urna at enim. Cras lobortis congue massa ut convallis. Vestibulum lacus magna, congue vitae ultrices id, laoreet non magna.

`Nam mattis tortor vitae augue posuere, a luctus urna tempus. Donec hendrerit ex mattis eros tempus porttitor. Praesent felis neque, porta ut tortor sed, pretium pharetra nisi. In et ligula arcu. Etiam nisl erat, viverra a augue quis, egestas aliquam nibh. Mauris ultrices ex vitae quam malesuada, at malesuada justo viverra. Mauris sed enim sit amet libero molestie consectetur ut quis risus. In nec suscipit metus. Donec accumsan pulvinar nisi, vitae iaculis justo pulvinar eget. Cras condimentum nisl et tincidunt suscipit. Maecenas aliquam mi malesuada, auctor quam vel, maximus orci.`

Suspendisse vulputate lectus in nunc auctor posuere. Aliquam feugiat egestas maximus. Integer dignissim rutrum dui at pharetra. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris elementum molestie eros at cursus. Curabitur ultricies, dui at pharetra dignissim, mauris turpis rutrum ipsum, vel condimentum ipsum felis nec tellus. Duis et malesuada quam, at volutpat sem. Nam congue hendrerit ex. Ut dapibus, lacus a consequat lacinia, nibh est fermentum ante, quis hendrerit arcu dolor vitae lorem. Nullam vestibulum erat sed nisi vestibulum, quis pharetra augue venenatis. Phasellus placerat gravida urna varius viverra. Vestibulum laoreet pellentesque lorem.

**Comment by mfachal** [comment]
wontfix

**Comment by Lartu** [comment]
sad sad i cryeverytim (T⌓T)

**Comment by dsocolobsky** [comment]
README added as you requested, please don't come near me or my family ever again. Thanks.

**Comment by Lartu** [comment]
im under ur bed

**Comment by Lartu** [comment]
(⁄ ⁄•⁄ω⁄•⁄ ⁄)

**Comment by Lartu** [comment]
thx btw bye
